name: Build and Run get_next_line with Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Docker Buildx (optional for advanced setups)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t get_next_line .

      # Step 4: Run Docker container and make changes
      - name: Run Docker container and make changes
        run: |
          docker run --name get_next_line -v $GITHUB_WORKSPACE:/app get_next_line bash -c "make && git add . && git commit -m 'Automated changes from Docker container'"

      # Step 5: Push changes back to GitHub
      - name: Push changes to GitHub
        run: |
          # Ensure Git is configured with the necessary user details
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          # Check for changes (this is mostly optional if step 4 commits)
          git status

          # Push changes back to GitHub
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Auto github token

