name: Build and Run get_next_line with Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Docker Buildx (required for Docker builds)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    # Step 3: Build the Docker image
    - name: Build Docker image
      run: |
        docker build -t get_next_line .

    # Step 4: Run the Docker container
    - name: Run Docker container
      run: |
        docker run --rm get_next_line
